# Generated by Django 4.2.6 on 2023-12-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='due_date',
        ),
    ]
